# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abhinav Kumar
full_name: Abhinav Kumar
email: abhinavkumar130503@gmail.com
email2: abhinav.coder131@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abhinavcode13.github.io" # the base hostname & protocol for your site
github_username:  abhinavcode13
twitter_username: abhinavxkumar13
linkedin_username: abhinav131
# stackoverflow: 
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from

# Default Open Graph image for social sharing
image: /assets/profile.jpg

defaults:
  - scope:
      path: ""
    values:
      image: /assets/profile.jpg
